ame: Node.js CI

on:
    push:
        branches-ignore:
            - master

jobs:
    run-tests:
        strategy:
            matrix:
                node-version: [14.x, 16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                os: [ubuntu-latest, windows-latest]

        runs-on: ${{matrix.os}}

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - name: run test
              run: npm test js1
              if: always()
            - run: npm run jest-report
              if: always()
            - uses: tanmen/jest-reporter@v1
              if: always()
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
